url: http://localhost:8080

servers:
  honojs:
    image_name: bun-honojs-image

  express:
    image_name: node-express-image

  nestjs:
    image_name: node-nestjs-image

  fastify:
    image_name: node-fastify-image

  fastapi:
    image_name: python-fastapi-image

  chi:
    image_name: go-chi-image

  fiber:
    image_name: go-fiber-image

  gin:
    image_name: go-gin-image
